### ISSUE TITLE
Consider amending tag description for next release

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-builder#173]
A small error in the tag description for [0.2.9](https://github.com/freedomofpress/securedrop-debian-packaging/releases/tag/0.2.9) was [spotted](https://github.com/freedomofpress/securedrop-debian-packages-lfs/pull/22#issuecomment-637051027) in final review of the packages. The version number for the securedrop-proxy package was specified in the description as 0.2.3, but it should be 0.3.0. This description error has no impact on the packages themselves, but we may want to amend the description in the next release cycle.

**Comment by legoktm** [comment]
It's unclear to me if this task was supposed to be for literally the next release, to correct a mistake in the previous one, or generic "next release" as if there's a bug in `scripts/generate-tag-message`.

**Comment by legoktm** [comment]
I'm closing this because our tags are now far simpler that this is unlikely to happen again. (And the script was deleted in 04b64817dbf59d7d1448ea82e79a1c574794c359.)
