### ISSUE TITLE
Remove RPM nightly build support

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-builder#186]
In #168 we disabled the nightly RPM builds in this repo, as we wanted to prioritize manually created RCs during releases over nightly builds. In practice, we've not missed the nightlies much: the RPM doesn't have a high rate of change, and is quick to build locally.

Additionally there are security considerations when shipping CI build artifacts to `dom0`. For this reason we prefer to always have the RPM manually built by a developer. We're also moving towards using the RPM for the `dev` scenario, which means we have to pay even greater attention to how and where it's built: 
https://github.com/freedomofpress/securedrop-workstation/pull/587

We should therefore remove the support for nightly RPM builds from our CI configuration (keeping it would imply that it is safe to enable again at a later date).

**Comment by legoktm** [comment]
This was done in 42a185fb22cbb4171e0e6695634c5f29a2cd1158.
