### ISSUE TITLE
Consistently use native packages for everything

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-builder#431]
https://wiki.debian.org/DebianMentorsFaq#What_is_the_difference_between_a_native_Debian_package_and_a_non-native_package.3F

Mostly by accident, we are using non-native packages for RCs because versioning scheme is "0.9.0-rc1". This meant that the diff between 0.9.0-rc3 and 0.9.0 included changes to things like the changelog because it switched from non-native to native.

We should ensure that we're consistently using native packages. Best way to do that is adjust the version to the standard "0.9.0~rc1".

**Comment by zenmonkeykstop** [comment]
Is this a docs change or can we add it as a regex? It feels like the former coz the nightly version format, but I guess we could match against (release|rc|nightly) as well.

**Comment by legoktm** [comment]
I was thinking of a `s/-/~/` regex yeah.
